[package]
name = "minigrep"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.42", features = ["derive"] }
owo-colors = { version = "4.2.2", features = ["supports-colors"] }
