[package]
name = "hello_macro"
version = "0.1.0"
edition = "2024"

# cargo add hello_macro_derive --optional --path hello_macro_derive
[dependencies]
hello_macro_derive = { version = "0.1.0", path = "hello_macro_derive", optional = true }

[features]
hello_macro_derive = ["dep:hello_macro_derive"]
